# Generated by Django 6.0 on 2026-02-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacherprofile_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_signatures/'),
        ),
    ]
