# Generated by Django 6.0.1 on 2026-04-07 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_principal_signature_school_stamp'),
        ('teachers', '0003_teacherprofile_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='staff_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='teacherprofile',
            constraint=models.UniqueConstraint(fields=('school', 'staff_id'), name='unique_staff_id_per_school'),
        ),
    ]
