# Generated by Django 5.2.2 on 2026-01-23 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('QUESTION', 'Exam/Test Questions'), ('NOTE', 'Lesson Note')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=50)),
                ('generated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_contents', to='teachers.teacherprofile')),
            ],
            options={
                'verbose_name': 'AI Generated Content',
                'verbose_name_plural': 'AI Generated Contents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('history', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='teachers.teacherprofile')),
            ],
        ),
    ]
