# Generated by Django 6.0 on 2026-01-23 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_studentresult_test1_alter_studentresult_test2'),
        ('ai_assistant', '0001_initial'),
        ('students', '0002_student_user'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBTMockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=50)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exams', to='academics.schoolclass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exams', to='teachers.teacherprofile')),
            ],
            options={
                'verbose_name': 'CBT Mock Exam',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CBTAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('objective_score', models.FloatField(default=0.0)),
                ('theory_feedback', models.JSONField(default=dict)),
                ('total_score', models.FloatField(default=0.0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_attempts', to='students.student')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ai_assistant.cbtmockexam')),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='CBTQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('OBJ', 'Objective'), ('THEORY', 'Theory/Essay')], max_length=10)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(blank=True, max_length=255, null=True)),
                ('option_b', models.CharField(blank=True, max_length=255, null=True)),
                ('option_c', models.CharField(blank=True, max_length=255, null=True)),
                ('option_d', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_option', models.CharField(blank=True, max_length=1, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ai_assistant.cbtmockexam')),
            ],
        ),
        migrations.CreateModel(
            name='CBTAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=1, null=True)),
                ('theory_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('score', models.FloatField(default=0.0)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ai_assistant.cbtattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_assistant.cbtquestion')),
            ],
        ),
    ]
