# Generated by Django 6.0 on 2026-01-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_academicsession_options_alter_scheme_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='motto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
