# Generated by Django 6.0 on 2026-02-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='principal_signature',
            field=models.ImageField(blank=True, help_text="Principal's signature", null=True, upload_to='school_signatures/'),
        ),
        migrations.AddField(
            model_name='school',
            name='stamp',
            field=models.ImageField(blank=True, help_text='School Official Stamp', null=True, upload_to='school_stamps/'),
        ),
    ]
