from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
import io

def generate_docx(content_obj):
    """
    Generates a .docx file from an AIContent object.
    Returns a BytesIO object containing the document data.
    """
    doc = Document()
    
    # Title
    title_text = f"{content_obj.get_content_type_display()}: {content_obj.subject}"
    title = doc.add_heading(title_text, 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Subtitles
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(f"Topic: {content_obj.topic} | Level: {content_obj.level}")
    run.italic = True
    run.font.size = Pt(11)

    doc.add_paragraph("_" * 50).alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph("\n")

    # Body Content
    # Simple markdown-like parsing for headers
    lines = content_obj.generated_text.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            doc.add_paragraph("")
            continue
            
        if line.startswith('### '):
            doc.add_heading(line[4:], level=3)
        elif line.startswith('## '):
            doc.add_heading(line[3:], level=2)
        elif line.startswith('# '):
            doc.add_heading(line[2:], level=1)
        elif line.startswith('**') and line.endswith('**'):
            p = doc.add_paragraph()
            p.add_run(line.strip('*')).bold = True
        else:
            doc.add_paragraph(line)

    # Footer
    doc.add_paragraph("\n")
    footer = doc.add_paragraph("Generated by SMRPS AI Assistant")
    footer.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    for run in footer.runs:
        run.font.size = Pt(8)
        run.font.color.rgb = None # Default greyish?

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer
