# Generated by Django 5.2.2 on 2026-01-05 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_classsubject_options_alter_schoolclass_options_and_more'),
        ('schools', '0002_alter_academicsession_options_alter_scheme_options_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsubject',
            options={},
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('First', 'First Term'), ('Second', 'Second Term'), ('Third', 'Third Term')], max_length=10)),
                ('test1', models.PositiveIntegerField(default=0)),
                ('test2', models.PositiveIntegerField(default=0)),
                ('exam', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(editable=False)),
                ('grade', models.CharField(editable=False, max_length=1)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.academicsession')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'unique_together': {('student', 'school_class', 'subject', 'academic_session', 'term')},
            },
        ),
    ]
