# Generated by Django 5.2.2 on 2026-01-05 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_classsubject_options_studentresult'),
        ('schools', '0002_alter_academicsession_options_alter_scheme_options_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermResultSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('First', 'First Term'), ('Second', 'Second Term'), ('Third', 'Third Term')], max_length=10)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('average', models.FloatField(default=0.0)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.academicsession')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_summaries', to='students.student')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('student', 'school_class', 'academic_session', 'term')},
            },
        ),
    ]
