# Generated by Django 5.2.2 on 2026-01-18 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_studentresult_exam_alter_studentresult_test1_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='form_teacher',
            field=models.ForeignKey(blank=True, help_text='The form teacher who publishes final results for this class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_classes', to='teachers.teacherprofile'),
        ),
    ]
