# Generated by Django 5.2.2 on 2026-01-19 10:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_schoolclass_form_teacher'),
        ('schools', '0002_alter_academicsession_options_alter_scheme_options_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='ca1',
            field=models.PositiveIntegerField(default=0, help_text='Continuous Assessment 1 (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='ca2',
            field=models.PositiveIntegerField(default=0, help_text='Continuous Assessment 2 (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='ca3',
            field=models.PositiveIntegerField(default=0, help_text='Continuous Assessment 3 (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='ca4',
            field=models.PositiveIntegerField(default=0, help_text='Continuous Assessment 4 (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='remark',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subject_highest',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subject_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='exam',
            field=models.PositiveIntegerField(default=0, help_text='Exam score (0-60)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='grade',
            field=models.CharField(default='F', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='ClassTermInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('First', 'First Term'), ('Second', 'Second Term'), ('Third', 'Third Term')], max_length=10)),
                ('class_population', models.PositiveIntegerField(default=0)),
                ('times_school_opened', models.PositiveIntegerField(default=0)),
                ('next_term_begins', models.DateField(blank=True, null=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.academicsession')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_info', to='academics.schoolclass')),
            ],
            options={
                'unique_together': {('school_class', 'academic_session', 'term')},
            },
        ),
        migrations.CreateModel(
            name='StudentAffectiveTraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('First', 'First Term'), ('Second', 'Second Term'), ('Third', 'Third Term')], max_length=10)),
                ('punctuality', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Pass'), ('E', 'E - Fair'), ('F', 'F - Fail')], default='C', max_length=1)),
                ('mental_alertness', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Pass'), ('E', 'E - Fair'), ('F', 'F - Fail')], default='C', max_length=1)),
                ('respect', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Pass'), ('E', 'E - Fair'), ('F', 'F - Fail')], default='C', max_length=1)),
                ('neatness', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Pass'), ('E', 'E - Fair'), ('F', 'F - Fail')], default='C', max_length=1)),
                ('honesty', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Pass'), ('E', 'E - Fair'), ('F', 'F - Fail')], default='C', max_length=1)),
                ('politeness', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Pass'), ('E', 'E - Fair'), ('F', 'F - Fail')], default='C', max_length=1)),
                ('relationship_with_peers', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Pass'), ('E', 'E - Fair'), ('F', 'F - Fail')], default='C', max_length=1)),
                ('willingness_to_learn', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Pass'), ('E', 'E - Fair'), ('F', 'F - Fail')], default='C', max_length=1)),
                ('spirit_of_teamwork', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Pass'), ('E', 'E - Fair'), ('F', 'F - Fail')], default='C', max_length=1)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.academicsession')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affective_traits', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Student Affective Traits',
                'unique_together': {('student', 'school_class', 'academic_session', 'term')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('First', 'First Term'), ('Second', 'Second Term'), ('Third', 'Third Term')], max_length=10)),
                ('times_present', models.PositiveIntegerField(default=0)),
                ('times_school_opened', models.PositiveIntegerField(default=0)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.academicsession')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'school_class', 'academic_session', 'term')},
            },
        ),
        migrations.CreateModel(
            name='StudentPsychomotorTraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('First', 'First Term'), ('Second', 'Second Term'), ('Third', 'Third Term')], max_length=10)),
                ('games_and_sports', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Pass'), ('E', 'E - Fair'), ('F', 'F - Fail')], default='C', max_length=1)),
                ('verbal_skills', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Pass'), ('E', 'E - Fair'), ('F', 'F - Fail')], default='C', max_length=1)),
                ('artistic_creativity', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Pass'), ('E', 'E - Fair'), ('F', 'F - Fail')], default='C', max_length=1)),
                ('musical_skills', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Pass'), ('E', 'E - Fair'), ('F', 'F - Fail')], default='C', max_length=1)),
                ('dance_skills', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Pass'), ('E', 'E - Fair'), ('F', 'F - Fail')], default='C', max_length=1)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.academicsession')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychomotor_traits', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Student Psychomotor Traits',
                'unique_together': {('student', 'school_class', 'academic_session', 'term')},
            },
        ),
        migrations.CreateModel(
            name='StudentTermReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('First', 'First Term'), ('Second', 'Second Term'), ('Third', 'Third Term')], max_length=10)),
                ('class_teacher_comment', models.TextField(blank=True)),
                ('class_teacher_name', models.CharField(blank=True, max_length=200)),
                ('principal_comment', models.TextField(blank=True)),
                ('next_term_begins', models.DateField(blank=True, null=True)),
                ('promotion_status', models.CharField(choices=[('PROMOTED', 'Promoted'), ('REPEATED', 'Repeated'), ('TRIAL', 'Trial Promotion'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.academicsession')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_reports', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Term Report',
                'verbose_name_plural': 'Student Term Reports',
                'unique_together': {('student', 'school_class', 'academic_session', 'term')},
            },
        ),
    ]
