# Generated by Django 6.0 on 2026-01-21 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_studentresult_ca1_studentresult_ca2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='test1',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Test 1'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='test2',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Test 2'),
        ),
    ]
