# Generated by Django 5.2.2 on 2026-01-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_termresultsummary_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtquestion',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Only published questions are visible to students.'),
        ),
    ]
