# Generated by Django 5.2.2 on 2026-01-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_cbtquestion_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtquestion',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Time allowed for this CBT exam (in minutes)'),
        ),
    ]
