# Generated by Django 5.2.2 on 2026-01-23 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_cbtquestion_duration'),
        ('schools', '0003_school_motto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbtquestion',
            name='duration',
        ),
        migrations.CreateModel(
            name='CBTExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(default=30, help_text='Time allowed for this CBT exam (in minutes)')),
                ('is_published', models.BooleanField(default=False, help_text='Only published exams are visible to students.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'unique_together': {('school_class', 'subject')},
            },
        ),
    ]
