# Generated by Django 5.2.2 on 2026-01-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_remove_cbtquestion_duration_cbtexam'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cbtexam',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cbtexam',
            name='cbt_type',
            field=models.CharField(choices=[('practice', 'Practice'), ('first_test', '1st Test'), ('second_test', '2nd Test'), ('exam', 'Exam')], default='practice', help_text='Type of CBT: practice, test, or exam.', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cbtexam',
            unique_together={('school_class', 'subject', 'cbt_type')},
        ),
    ]
