# Generated by Django 6.0.1 on 2026-05-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_alter_cbtexam_unique_together_cbtexam_cbt_type_and_more'),
        ('schools', '0004_school_principal_signature_school_stamp'),
        ('students', '0003_student_date_of_birth_student_gender'),
        ('teachers', '0004_alter_teacherprofile_staff_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cbtresponse',
            unique_together={('session', 'question')},
        ),
        migrations.AddIndex(
            model_name='cbtquestion',
            index=models.Index(fields=['school_class', 'subject', 'is_published'], name='academics_c_school__134d41_idx'),
        ),
        migrations.AddIndex(
            model_name='cbtquestion',
            index=models.Index(fields=['school', 'is_published'], name='academics_c_school__66ef93_idx'),
        ),
        migrations.AddIndex(
            model_name='cbtresponse',
            index=models.Index(fields=['session', 'is_correct'], name='academics_c_session_6fd61f_idx'),
        ),
        migrations.AddIndex(
            model_name='cbtsession',
            index=models.Index(fields=['student', 'completed_at'], name='academics_c_student_2a64e5_idx'),
        ),
        migrations.AddIndex(
            model_name='cbtsession',
            index=models.Index(fields=['school_class', 'subject', 'completed_at'], name='academics_c_school__1952c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='cbtsession',
            constraint=models.UniqueConstraint(condition=models.Q(('completed_at__isnull', True)), fields=('student', 'school_class', 'subject'), name='unique_incomplete_cbt_session'),
        ),
    ]
